export function buildRunOpsCtx({
  bridge,
  runState,
  graphRuntime,
  dataActions,
  runActions,
  selectionActions,
  runtimeDebug,
  graphDomain,
  hasPausedRun,
  dataState,
  uiActions,
  uiState,
}) {
  return {
    bridge,
    liveMode: runState.liveMode,
    anyRunActive: graphRuntime.anyRunActive,
    statusResetActive: runState.statusResetActive,
    selectedRunId: runState.selectedRunId,
    activeRunId: runState.activeRunId,
    setLogs: dataActions.setLogs,
    setStartup: dataActions.setStartup,
    setTests: dataActions.setTests,
    setStatusById: dataActions.setStatusById,
    setRuns: dataActions.setRuns,
    applyDataSnapshot: dataActions.applyDataSnapshot,
    setActiveRunId: runActions.setActiveRunId,
    setSelectedRunId: runActions.setSelectedRunId,
    setWaitingFirstEvent: runActions.setWaitingFirstEvent,
    setLastRunUpdateTs: runActions.setLastRunUpdateTs,
    setStatusResetActive: runActions.setStatusResetActive,
    setSelectedSuiteId: selectionActions.setSelectedSuiteId,
    setSelectedTestId: selectionActions.setSelectedTestId,
    setSelectedCaseId: selectionActions.setSelectedCaseId,
    lastRunUpdateTs: runState.lastRunUpdateTs,
    loadingRun: runState.loadingRun,
    setLoadingRun: runActions.setLoadingRun,
    idsForRun: graphRuntime.idsForRun,
    runtimeDebug,
    graphState: graphDomain.graphState,
    graphScope: graphDomain.graphScope,
    manualGraphChildId: graphDomain.manualGraphChildId,
    graphDetailChildId: graphRuntime.graphDetailChildId,
    setPreviewBusy: runActions.setPreviewBusy,
    setPreviewLine: runActions.setPreviewLine,
    activeRunRow: graphRuntime.activeRunRow,
    runs: dataState.runs,
    setPausedRunState: runActions.setPausedRunState,
    pausedRunState: runState.pausedRunState,
    hasPausedRun,
    tests: dataState.tests,
    runAutoTrackRef: graphDomain.runAutoTrackRef,
    setRunScopeEnabled: runActions.setRunScopeEnabled,
    setLiveMode: runActions.setLiveMode,
    setFollowActivePaused: graphDomain.setFollowActivePaused,
    setGraphScope: graphDomain.setGraphScope,
    setChildScopeEvents: graphDomain.setChildScopeEvents,
    setChildProgressByParent: graphDomain.setChildProgressByParent,
    setShowUtilityMenu: uiActions.setShowUtilityMenu,
    tab: uiState.tab,
    setDrawerOpen: uiActions.setDrawerOpen,
    setGraphDetailsOpen: graphDomain.setGraphDetailsOpen,
  };
}

