export function buildGraphRuntimeCtx({
  runtimeDebug,
  bridge,
  uiState,
  graphModel,
  graphDomain,
  runState,
  dataState,
  dataActions,
  selectionState,
  filters,
}) {
  return {
    runtimeDebug,
    bridge,
    tab: uiState.tab,
    graphModel,
    graphState: graphDomain.graphState,
    setGraphState: graphDomain.setGraphState,
    graphScope: graphDomain.graphScope,
    setGraphScope: graphDomain.setGraphScope,
    graphScopedModel: graphDomain.graphScopedModel,
    selectedRunId: runState.selectedRunId,
    activeRunId: runState.activeRunId,
    runs: dataState.runs,
    statusById: dataState.statusById,
    setStatusById: dataActions.setStatusById,
    tests: dataState.tests,
    followActiveChild: graphDomain.followActiveChild,
    followActivePaused: graphDomain.followActivePaused,
    setFollowActivePaused: graphDomain.setFollowActivePaused,
    manualGraphChildId: graphDomain.manualGraphChildId,
    setManualGraphChildId: graphDomain.setManualGraphChildId,
    graphSelectedRunTargetId: graphDomain.graphSelectedRunTargetId,
    aggregateFilterIds: selectionState.aggregateFilterIds,
    aggregateFilterOptions: filters.aggregateFilterOptions,
    setGraphBubbleAggregateId: graphDomain.setGraphBubbleAggregateId,
    aggregateScopedSuites: filters.aggregateScopedSuites,
    selectedCaseId: selectionState.selectedCaseId,
    selectedCaseIds: selectionState.selectedCaseIds,
    selectedTestId: selectionState.selectedTestId,
    childScopeEvents: graphDomain.childScopeEvents,
    setChildScopeEvents: graphDomain.setChildScopeEvents,
    childProgressByParent: graphDomain.childProgressByParent,
    setChildProgressByParent: graphDomain.setChildProgressByParent,
    runAutoTrackRef: graphDomain.runAutoTrackRef,
    setGraphDetailsOpen: graphDomain.setGraphDetailsOpen,
  };
}

