export const LAYOUT_CONSTANTS = {
  SUITES_MIN_PX: 260,
  CASES_MIN_PX: 420,
  DETAILS_MIN_PX: 360,
  DIVIDER_PX: 10,
  OVERLAY_DETAILS_MIN_PX: 320,
  GRAPH_DIVIDER_PX: 10,
  GRAPH_RIGHT_MIN_PX: 320,
  GRAPH_RIGHT_MAX_PX: 520,
  GRAPH_CENTER_MIN_PX: 520,
};

