from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "ui" / "src" / "capabilities" / "source.json"
OUT_SCHEMA = ROOT / "ui" / "src" / "capabilities" / "generated" / "schema.ts"
OUT_REGISTRY = ROOT / "ui" / "src" / "capabilities" / "generated" / "registry.json"
OUT_DOC_CANONICAL = ROOT / "ui" / "src" / "capabilities" / "generated" / "AGENT_CAPABILITIES.md"
OUT_DOC_MIRROR = ROOT / "docs" / "AGENT_CAPABILITIES.md"


def _ts_type(param_type: str) -> str:
    mapping = {
        "string": "string",
        "number": "number",
        "boolean": "boolean",
        "string[]": "string[]",
        "number[]": "number[]",
    }
    return mapping.get(param_type, "unknown")


def _safe_type_name(action_id: str) -> str:
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in action_id)
    while "__" in cleaned:
        cleaned = cleaned.replace("__", "_")
    return f"Action_{cleaned.upper()}"


def generate_schema(pages: list[dict[str, Any]]) -> str:
    lines: list[str] = [
        "// Auto-generated by scripts/generate_capabilities.py. Do not edit manually.",
        "",
    ]
    type_names: list[str] = []
    for page in pages:
        for action in page.get("actions", []):
            action_id = str(action.get("id", "")).strip()
            if not action_id:
                continue
            type_name = _safe_type_name(action_id)
            type_names.append(type_name)
            lines.append(f"export interface {type_name} {{")
            lines.append(f"  action: '{action_id}';")
            for param in action.get("params", []):
                name = str(param.get("name", "")).strip()
                if not name:
                    continue
                required = bool(param.get("required", False))
                optional = "" if required else "?"
                param_type = _ts_type(str(param.get("type", "string")))
                lines.append(f"  {name}{optional}: {param_type};")
            lines.append("}")
            lines.append("")

    union = " | ".join(type_names) if type_names else "never"
    lines.append(f"export type UIAction = {union};")
    lines.append("")
    lines.append("export type CapabilityActionEnvelope = {")
    lines.append("  actions: UIAction[];")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def generate_markdown(pages: list[dict[str, Any]]) -> str:
    out: list[str] = [
        "# UI Capabilities Reference",
        "",
        "> Auto-generated. Do not edit manually.",
        "",
        "## Pages",
        "",
    ]
    for page in pages:
        title = page.get("title", page.get("pageId", "Untitled"))
        route = page.get("route", "")
        out.append(f"### {title} (`{route}`)")
        out.append("")
        out.append(str(page.get("description", "")).strip())
        out.append("")

        actions = page.get("actions", [])
        if actions:
            out.append("#### Actions")
            out.append("")
            out.append("| Action ID | Description | Parameters | Conditions |")
            out.append("|-----------|-------------|------------|------------|")
            for action in actions:
                action_id = str(action.get("id", "")).strip()
                desc = str(action.get("description", "")).replace("\n", " ").strip()
                params = action.get("params", [])
                if params:
                    rendered_params = ", ".join(
                        f"`{p.get('name','')}` ({p.get('type','string')}{'' if p.get('required',False) else '?'})"
                        for p in params
                    )
                else:
                    rendered_params = "-"
                conditions = action.get("conditions", [])
                rendered_conditions = (
                    "; ".join(str(c.get("description", "")).strip() for c in conditions if c.get("description"))
                    if conditions
                    else "-"
                )
                destructive_note = " [destructive]" if action.get("destructive", False) else ""
                out.append(
                    f"| `{action_id}`{destructive_note} | {desc} | {rendered_params} | {rendered_conditions} |"
                )
            out.append("")

        filters = page.get("filters", [])
        if filters:
            out.append("#### Filters")
            out.append("")
            out.append("| Filter ID | Type | Description |")
            out.append("|-----------|------|-------------|")
            for filter_cap in filters:
                out.append(
                    f"| `{filter_cap.get('id','')}` | {filter_cap.get('type','')} | {str(filter_cap.get('description','')).strip()} |"
                )
            out.append("")
    return "\n".join(out)


def generate_docs_index() -> str:
    return "\n".join(
        [
            "---",
            'title: "Agent Capabilities"',
            'summary: "Capability-based UI action catalog and generation workflow."',
            "---",
            "",
            "# Agent Capabilities",
            "",
            "The canonical generated capability reference is:",
            "",
            "- `ui/src/capabilities/generated/AGENT_CAPABILITIES.md`",
            "",
            "Related generated artifacts:",
            "",
            "- `ui/src/capabilities/generated/registry.json`",
            "- `ui/src/capabilities/generated/schema.ts`",
            "",
            "Regenerate with:",
            "",
            "- `npm --prefix ui run generate:capabilities`",
            "",
            "Notes:",
            "",
            "- Some environments deny subprocess writes to `docs/`.",
            "- Use `python scripts/generate_capabilities.py --strict-docs-mirror` in CI/release if docs mirror write must succeed.",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--strict-docs-mirror",
        action="store_true",
        help="Fail if docs/AGENT_CAPABILITIES.md mirror cannot be written.",
    )
    args = parser.parse_args()

    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise RuntimeError("Capability source must be an array")

    OUT_SCHEMA.parent.mkdir(parents=True, exist_ok=True)
    OUT_REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    OUT_DOC_CANONICAL.parent.mkdir(parents=True, exist_ok=True)

    schema = generate_schema(data)
    markdown = generate_markdown(data)

    OUT_SCHEMA.write_text(schema, encoding="utf-8")
    OUT_REGISTRY.write_text(json.dumps(data, indent=2), encoding="utf-8")
    OUT_DOC_CANONICAL.write_text(markdown, encoding="utf-8")

    docs_index = generate_docs_index()
    mirror_written = False
    try:
        OUT_DOC_MIRROR.parent.mkdir(parents=True, exist_ok=True)
        OUT_DOC_MIRROR.write_text(docs_index, encoding="utf-8")
        mirror_written = True
    except PermissionError:
        print(
            f"Warning: could not write docs mirror at {OUT_DOC_MIRROR} (permission denied). "
            f"Canonical output written to {OUT_DOC_CANONICAL}.",
            file=sys.stderr,
        )
        if args.strict_docs_mirror:
            raise RuntimeError(
                "strict docs mirror enabled and docs/AGENT_CAPABILITIES.md could not be written"
            )

    print(f"Generated: {OUT_SCHEMA}")
    print(f"Generated: {OUT_REGISTRY}")
    print(f"Generated: {OUT_DOC_CANONICAL}")
    print(
        "Generated: "
        + (str(OUT_DOC_MIRROR) if mirror_written else f"{OUT_DOC_MIRROR} (skipped mirror write)")
    )


if __name__ == "__main__":
    main()
